" **************************************************
" pathogen配置
" **************************************************
call pathogen#infect()
call pathogen#helptags()

" **************************************************
" 文件语法配置
" **************************************************
syntax on
filetype plugin indent on

"
" Tagbar配置
"
nmap <F2> :TagbarToggle<CR>   "设置快捷键  
let g:tagbar_width = 20       "设置宽度，默认为40  
let g:tagbar_left = 1         "在左侧"  
"let g:tagbar_right = 1        "在右侧  
autocmd VimEnter * nested :call tagbar#autoopen(1)    "打开vim时自动打开  


" **************************************************
" NERDTree配置
" **************************************************
map <F3> :NERDTreeMirror<CR>
map <F3> :NERDTreeToggle<CR>
let g:NERDTreeWinPos="right"     "在右侧
"let g:NERDTreeWinPos="left"    "在左侧
let g:NERDTreeWinSize=30
let g:NERDTreeShowLineNumbers=1
let g:neocomplcache_enable_at_startup = 1
autocmd VimEnter * NERDTree


" **************************************************
" vim常用配置
" **************************************************
set cursorline    "突出显示当前行
"set cursorcolumn  "突出显示当前列
set ruler 	  "在右下角显示光标位置的状态行
set autoindent    "自动缩进
set tabstop=4       "tab键缩进为4
set expandtab     "tab键展开
set number

